version: "4.3"

services:
    rekan_be-app:
        build:
            context: "."
        container_name: rekan_be-app
        ports:
            - 3021:3021
        networks:
            backend:
                aliases:
                    - app

networks:
    backend:
        name: rekan_be-network